version: '3'

services:
  pygeoapi:
    build: 
      context: pygeoapi
    ports:
      - 5000:80
    # volumes:
    #   - ./pygeoapi/pygeoapi.config.yml:/pygeoapi/local.config.yml
    environment:
      - PYGEOAPI_URL=http://localhost:5000
